language: php

dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer require satooshi/php-coveralls
  - composer install --prefer-source

script:
  - composer test

after_success:
  - if [[ $(phpenv version-name) == '7.1' ]]; then php vendor/bin/coveralls -v; fi
