language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls
  - composer install --prefer-source

script:
  - composer test

after_script:
  - php vendor/bin/coveralls -v
