language: php

dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - composer self-update
  - composer require satooshi/php-coveralls --ignore-platform-reqs
  - composer install --prefer-source --ignore-platform-reqs

script:
  - composer test

after_success:
  - if [[ $(phpenv version-name) == '7.1' ]]; then php vendor/bin/coveralls -v; fi
